// The navigation bar on the left with clickable icons.

component SideBarItem {
    in property <image> icon;
    property <bool> is-hovered: touch-area.has-hover;
    in property <bool> is-active: false;
    touch-area := TouchArea {
        width: 50px;
        height: 35px;
    }

    callback is-clicked <=> touch-area.clicked;
    img := Image {
        source: icon;
        colorize: is-hovered || is-active ? whitesmoke : darkgray;
        height: 25px;
        width: 25px;
    }
}

export component SideBar inherits Rectangle {
    width: 50px;
    property <bool> active1: true;
    property <bool> active2: false;
    property <bool> active3: false;
    callback switch-view(view: string);
    HorizontalLayout {
        VerticalLayout {
            VerticalLayout {
                alignment: start;
                HorizontalLayout {
                    padding-top: 10px;
                    padding-bottom: 20px;
                    alignment: center;
                    SideBarItem1 := SideBarItem {
                        icon: @image-url("../assets/home.svg");
                        is-clicked => {
                            active1 = true;
                            active2 = false;
                            active3 = false;
                            switch-view("home")
                        }
                        is-active: active1;
                    }
                }

                HorizontalLayout {
                    alignment: center;
                    SideBarItem2 := SideBarItem {
                        icon: @image-url("../assets/library.svg");
                        is-clicked => {
                            active1 = false;
                            active2 = true;
                            active3 = false;
                            switch-view("library")
                        }
                        is-active: active2;
                    }
                }
            }

            VerticalLayout {
                alignment: end;
                HorizontalLayout {
                    padding-bottom: 10px;
                    alignment: center;
                    SideBarItem3 := SideBarItem {
                        icon: @image-url("../assets/settings.svg");
                        is-clicked => {
                            active1 = false;
                            active2 = false;
                            active3 = true;
                            switch-view("settings")
                        }
                        is-active: active3;
                    }
                }
            }
        }

        vertical-split-line := Rectangle {
            width: 1px;
            background: #363434;
        }
    }
}
