// CurrentView determines which view to show alongside the SideBar.

import { Home } from "home.slint";
import { Library } from "library.slint";
import { Reader } from "reader.slint";
import { Settings } from "settings.slint";

export component CurrentView inherits Rectangle {
    in property <string> view;
    if view == "home": Home { }
    if view == "library": Library { }
    if view == "reader": Reader { }
    if view == "settings": Settings { }
}
