// LibraryView is the scrollable grid which contains all comics in the user's library locations.

export component Library {
    VerticalLayout {
        alignment: center;
        Text {
            horizontal-alignment: center;
            text: "Library";
            font-size: 40px;
        }

        Text {
            horizontal-alignment: center;
            text: "No library yet :)";
            font-size: 20px;
        }
    }
}
