import { TabWidget } from "std-widgets.slint";
import { HomeView, LibraryView, SettingsView } from "views/views.slint";

export component MainWindow inherits Window {
    preferred-height: 480px;
    preferred-width: 640px;
    title: "Stella (Early Development)";
    TabWidget {
        Tab {
            title: "Home";
            HomeView { }
        }

        Tab {
            title: "Library";
            LibraryView { }
        }

        Tab {
            title: "Settings";
            SettingsView { }
        }
    }
}
